# Generated by Django 5.2.6 on 2025-11-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chargers", "0003_chargepoint_chargers_ch_site_id_1bdbfa_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connector",
            name="id_from_source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(
            lambda apps, _: apps.get_model("chargers", "Connector")
            .objects.filter(id_from_source="")
            .update(id_from_source=None)
        ),
        migrations.AddConstraint(
            model_name="chargepoint",
            constraint=models.UniqueConstraint(
                fields=("site", "id_from_source"), name="unique_chargepoint_per_site"
            ),
        ),
        migrations.AddConstraint(
            model_name="chargingsite",
            constraint=models.UniqueConstraint(
                fields=("data_source", "id_from_source"), name="unique_site_per_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="connector",
            constraint=models.UniqueConstraint(
                fields=("chargepoint", "id_from_source"),
                name="unique_connector_per_chargepoint",
                nulls_distinct=True,
            ),
        ),
    ]
