# Generated by Django 5.2.6 on 2025-11-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chargers", "0004_alter_connector_id_from_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargepoint",
            name="id_from_source",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="connector",
            name="id_from_source",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
