# Generated by Django 5.2.9 on 2025-12-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chargers", "0005_alter_chargepoint_id_from_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connector",
            name="connector_type",
            field=models.CharField(
                choices=[
                    ("Type 1", "Type 1"),
                    ("CCS Type 1", "CCS Type 1"),
                    ("Type 2", "Type 2"),
                    ("CCS Type 2", "CCS Type 2"),
                    ("Type 3A", "Type 3A"),
                    ("Type 3C", "Type 3C"),
                    ("CHAdeMO", "CHAdeMO"),
                    ("MCS", "MCS"),
                    ("Schuko", "Schuko (Type F)"),
                    ("NACS", "NACS (Tesla US)"),
                    ("Tesla Supercharger EU", "Tesla Supercharger EU (Type 2)"),
                    ("Tesla Roadster HPC", "Tesla Roadster HPC"),
                    ("iec60309x2single16", "CEE single-phase 16 A"),
                    ("iec60309x2three16", "CEE three-phase 16 A"),
                    ("iec60309x2three32", "CEE three-phase 32 A"),
                    ("iec60309x2three64", "CEE three-phase 63 A"),
                    ("other", "Other"),
                ],
                max_length=255,
            ),
        ),
    ]
