# Generated by Django 5.2.9 on 2026-01-02 18:15

from django.db import migrations, models

import evmap_backend.chargers.fields


class Migration(migrations.Migration):

    dependencies = [
        ("chargers", "0006_alter_connector_connector_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "evse_operator_id",
                    evmap_backend.chargers.fields.EVSEOperatorIDField(
                        blank=True, max_length=5, unique=True
                    ),
                ),
                ("website", models.URLField(blank=True)),
            ],
        ),
    ]
