# Generated by Django 5.2.9 on 2026-01-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chargers", "0007_network"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="network",
            index=models.Index(
                fields=["evse_operator_id"], name="chargers_ne_evse_op_9e9c6a_idx"
            ),
        ),
    ]
