# Generated by Django 5.2.9 on 2026-01-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chargers", "0008_network_chargers_ne_evse_op_9e9c6a_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargingsite",
            name="license_attribution",
            field=models.TextField(blank=True),
        ),
    ]
