# Generated by Django 5.2.6 on 2026-01-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chargers", "0010_chargingsite_license_attribution_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargepoint",
            name="physical_reference",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
