# Generated by Django 5.2.6 on 2026-02-15 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chargers", "0011_chargepoint_physical_reference"),
    ]

    operations = [
        migrations.RemoveField(model_name="chargingsite", name="network"),
        migrations.AddField(
            model_name="chargingsite",
            name="network",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chargers.network",
            ),
        ),
    ]
