# Generated by Django 6.0.3 on 2026-03-10 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chargers", "0012_alter_chargingsite_network"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargingsite",
            name="network",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chargingsites",
                to="chargers.network",
            ),
        ),
    ]
