# Generated by Django 6.0.3 on 2026-03-13 21:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chargers", "0014_alter_connector_connector_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargingsite",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True, srid=4326
            ),
        ),
    ]
