# Generated by Django 6.0.3 on 2026-03-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chargers", "0015_alter_chargingsite_location"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chargepoint",
            index=models.Index(
                fields=["site", "evseid"], name="chargers_ch_site_id_380e9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chargepoint",
            index=models.Index(fields=["evseid"], name="chargers_ch_evseid_dff81a_idx"),
        ),
    ]
