# Generated by Django 6.0.3 on 2026-03-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chargers", "0015_alter_chargingsite_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="connector",
            name="is_dc",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
