# Generated by Django 6.0.3 on 2026-04-01 20:30

import django.contrib.gis.db.models.fields
import django.contrib.gis.db.models.functions
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chargers", "0016_chargepoint_chargers_ch_site_id_380e9a_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargingsite",
            name="location_mercator",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.gis.db.models.functions.Transform(
                    django.db.models.functions.comparison.Cast(
                        "location",
                        django.contrib.gis.db.models.fields.GeometryField(srid=4326),
                    ),
                    3857,
                ),
                output_field=django.contrib.gis.db.models.fields.PointField(srid=3857),
            ),
        ),
    ]
