# Generated by Django 6.0.3 on 2026-04-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chargers", "0017_chargingsite_location_mercator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connector",
            name="connector_type",
            field=models.CharField(
                choices=[
                    ("Type 1", "Type 1"),
                    ("CCS Type 1", "CCS Type 1"),
                    ("Type 2", "Type 2"),
                    ("CCS Type 2", "CCS Type 2"),
                    ("Type 3A", "Type 3A"),
                    ("Type 3C", "Type 3C"),
                    ("CHAdeMO", "CHAdeMO"),
                    ("MCS", "MCS"),
                    ("Schuko", "Schuko (Type F)"),
                    ("Domestic J", "Domestic (Type J - Switzerland Type 13)"),
                    ("Domestic E", "Domestic (Type E - France, Belgium)"),
                    ("NACS", "NACS (Tesla US)"),
                    ("Tesla Supercharger EU", "Tesla Supercharger EU (Type 2)"),
                    ("Tesla Roadster HPC", "Tesla Roadster HPC"),
                    ("iec60309x2single16", "CEE single-phase 16 A"),
                    ("iec60309x2three16", "CEE three-phase 16 A"),
                    ("iec60309x2three32", "CEE three-phase 32 A"),
                    ("iec60309x2three64", "CEE three-phase 63 A"),
                    ("other", "Other"),
                ],
                max_length=255,
            ),
        ),
    ]
