# Generated by Django 6.0.3 on 2026-04-21 22:36

import django.contrib.gis.db.models.fields
import django.contrib.gis.db.models.functions
import django.db.models.functions.comparison
from django.db import migrations

import evmap_backend.chargers.fields


class Migration(migrations.Migration):
    dependencies = [
        ("chargers", "0018_alter_connector_connector_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargingsite",
            name="location_mercator",
            field=evmap_backend.chargers.fields.GeneratedSpatialField(
                db_persist=True,
                expression=django.contrib.gis.db.models.functions.Transform(
                    django.db.models.functions.comparison.Cast(
                        "location",
                        django.contrib.gis.db.models.fields.GeometryField(srid=4326),
                    ),
                    3857,
                ),
                output_field=django.contrib.gis.db.models.fields.PointField(srid=3857),
                srid=4326,
            ),
        ),
    ]
