# Generated by Django 6.0.3 on 2026-04-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chargers", "0019_alter_chargingsite_location_mercator"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="connector",
            index=models.Index(
                fields=["chargepoint", "-max_power"],
                name="chargers_co_chargep_0c31b6_idx",
            ),
        ),
    ]
