# Generated by Django 5.1.8 on 2025-05-25 15:06

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChargeLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("position", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("network", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="EVSE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evse_id", models.CharField(blank=True, max_length=255)),
                (
                    "chargelocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aggregator.chargelocation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Connector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("type1", "Type 1"),
                            ("type2_socket", "Type 2 (socket)"),
                            ("type2_plug", "Type 2 (plug)"),
                            ("type3a", "Type 3A"),
                            ("type3c", "Type 3C"),
                            ("schuko", "Schuko"),
                            ("cee_blue", "CEE Blue"),
                            ("cee_red", "CEE Red"),
                            ("chademo", "CHAdeMO"),
                            ("ccs1", "CCS Type 1"),
                            ("ccs2", "CCS Type 2"),
                            (
                                "tesla_dc_europe",
                                "Tesla Supercharger Europe (DC through Type 2)",
                            ),
                            ("tesla_roadster", "Tesla Roadster HPC"),
                            ("nacs", "NACS"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("power", models.FloatField()),
                (
                    "evse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aggregator.evse",
                    ),
                ),
            ],
        ),
    ]
