# Generated by Django 5.1.8 on 2025-09-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connector",
            name="type",
            field=models.CharField(
                choices=[
                    ("type1", "Type 1"),
                    ("type2_socket", "Type 2 (socket)"),
                    ("type2_plug", "Type 2 (plug)"),
                    ("type3a", "Type 3A"),
                    ("type3c", "Type 3C"),
                    ("gbt_ac", "GB/T AC"),
                    ("schuko", "Schuko"),
                    ("cee_blue", "CEE Blue"),
                    ("cee_red", "CEE Red"),
                    ("ccs1", "CCS Type 1"),
                    ("ccs2", "CCS Type 2"),
                    ("chademo", "CHAdeMO"),
                    ("gbt_dc", "GB/T DC"),
                    (
                        "tesla_dc_europe",
                        "Tesla Supercharger Europe (DC through Type 2)",
                    ),
                    ("tesla_roadster", "Tesla Roadster HPC"),
                    ("nacs", "NACS"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
