# Generated by Django 5.1.5 on 2025-02-01 20:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OsmNode",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("timestamp", models.DateTimeField()),
                ("version", models.IntegerField()),
                ("user", models.CharField(max_length=255)),
                ("uid", models.BigIntegerField()),
                ("tags", models.JSONField()),
            ],
        ),
    ]
