# Generated by Django 5.1.5 on 2025-02-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openstreetmap", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OsmUpdateState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_update", models.DateTimeField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
