repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.15.10
  hooks:
    - id: ruff-check
      name: run ruff linter
    - id: ruff-check
      name: sort imports with ruff
      args: [ --select, I, --fix ]
    - id: ruff-format
      name: run ruff formatter