# Generated by Django 5.1.8 on 2025-05-03 13:45

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("datex2", "0001_initial"),
        ("datex2", "0002_datex2refillpoint_id_from_source"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Datex2EnergyInfrastructureSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_from_source", models.CharField(max_length=255)),
                ("source", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("operatorName", models.CharField(max_length=255)),
                ("operatorPhone", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Datex2RefillPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("externalIdentifier", models.CharField(max_length=255)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datex2.datex2energyinfrastructuresite",
                    ),
                ),
                ("id_from_source", models.CharField(default="", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Datex2Connector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connector_type",
                    models.CharField(
                        choices=[
                            ("chademo", "CHAdeMO"),
                            ("cee3", "CEE3"),
                            ("cee5", "CEE5"),
                            ("yazaki", "Yazaki"),
                            ("domestic", "Domestic"),
                            ("domesticA", "Domestic A"),
                            ("domesticB", "Domestic B"),
                            ("domesticC", "Domestic C"),
                            ("domesticD", "Domestic D"),
                            ("domesticE", "Domestic E"),
                            ("domesticF", "Domestic F"),
                            ("domesticG", "Domestic G"),
                            ("domesticH", "Domestic H"),
                            ("domesticI", "Domestic I"),
                            ("domesticJ", "Domestic J"),
                            ("domesticK", "Domestic K"),
                            ("domesticL", "Domestic L"),
                            ("domesticM", "Domestic M"),
                            ("domesticN", "Domestic N"),
                            ("domesticO", "Domestic O"),
                            ("iec60309x2single16", "CEE single-phase 16 A"),
                            ("iec60309x2three16", "CEE three-phase 16 A"),
                            ("iec60309x2three32", "CEE three-phase 32 A"),
                            ("iec60309x2three64", "CEE three-phase 63 A"),
                            ("iec62196T1", "Type 1"),
                            ("iec62196T1COMBO", "CCS Type 1"),
                            ("iec62196T2", "Type 2"),
                            ("iec62196T2COMBO", "CCS Type 2"),
                            ("iec62196T3A", "Type 3A"),
                            ("iec62196T3C", "Type 3C"),
                            ("pantographBottomUp", "Pantograph bottom-up"),
                            ("pantographTopDown", "Pantograph top-down"),
                            ("teslaConnectorEurope", "Tesla Connector Europe"),
                            ("teslaConnectorAmerica", "NACS"),
                            ("teslaR", "Tesla Roadster DC"),
                            ("teslaS", "Tesla S"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "charging_mode",
                    models.CharField(
                        choices=[
                            ("mode1AC1p", "Mode 1 - AC single-phase"),
                            ("mode1AC3p", "Mode 1 - AC three-phase"),
                            ("mode2AC1p", "Mode 2 - AC single-phase"),
                            ("mode2AC3p", "Mode 2 - AC three-phase"),
                            ("mode3AC3p", "Mode 3 - AC three-phase"),
                            ("mode4DC", "Mode 4 - DC"),
                            ("legacyInductive", "Legacy Inductive"),
                            ("ccs", "CCS"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=255,
                    ),
                ),
                ("max_power", models.IntegerField()),
                (
                    "refill_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datex2.datex2refillpoint",
                    ),
                ),
            ],
        ),
    ]
