# Generated by Django 5.2.9 on 2025-12-28 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chargers", "0006_alter_connector_connector_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealtimeStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("BLOCKED", "Blocked"),
                            ("CHARGING", "Charging"),
                            ("INOPERATIVE", "Inoperative"),
                            ("OUTOFORDER", "Out of order"),
                            ("PLANNED", "Planned"),
                            ("REMOVED", "Removed"),
                            ("RESERVED", "Reserved"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("data_source", models.CharField(max_length=255)),
                (
                    "chargepoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chargers.chargepoint",
                    ),
                ),
            ],
        ),
    ]
