# Generated by Django 5.2.9 on 2025-12-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chargers", "0006_alter_connector_connector_type"),
        ("realtime", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="realtimestatus",
            options={"get_latest_by": "timestamp"},
        ),
        migrations.AddIndex(
            model_name="realtimestatus",
            index=models.Index(
                fields=["chargepoint", "timestamp"],
                name="realtime_re_chargep_5556d8_idx",
            ),
        ),
    ]
