# Generated by Django 5.2.9 on 2025-12-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realtime", "0002_alter_realtimestatus_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realtimestatus",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
