# Generated by Django 5.2.9 on 2026-01-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realtime", "0004_realtimestatus_license_attribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="realtimestatus",
            name="license_attribution_link",
            field=models.URLField(blank=True),
        ),
    ]
