# Generated by Django 6.0.3 on 2026-03-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chargers", "0015_alter_chargingsite_location"),
        ("realtime", "0005_realtimestatus_license_attribution_link"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="realtimestatus",
            name="realtime_re_chargep_5556d8_idx",
        ),
        migrations.AddIndex(
            model_name="realtimestatus",
            index=models.Index(
                fields=["chargepoint", "-timestamp"],
                name="realtime_re_chargep_a4c9dc_idx",
            ),
        ),
    ]
