# Generated by Django 6.0.3 on 2026-03-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chargers", "0016_chargepoint_chargers_ch_site_id_380e9a_idx_and_more"),
        (
            "realtime",
            "0006_remove_realtimestatus_realtime_re_chargep_5556d8_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="realtimestatus",
            index=models.Index(
                fields=["data_source", "-timestamp"],
                name="realtime_re_data_so_2b283c_idx",
            ),
        ),
    ]
