# Generated by Django 6.0.3 on 2026-03-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chargers", "0016_chargepoint_chargers_ch_site_id_380e9a_idx_and_more"),
        ("realtime", "0007_realtimestatus_realtime_re_data_so_2b283c_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="realtimestatus",
            index=models.Index(
                fields=["data_source", "chargepoint", "-timestamp"],
                name="realtime_re_data_so_aa3e1f_idx",
            ),
        ),
    ]
