# Generated by Django 6.0.3 on 2026-04-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chargers", "0018_alter_connector_connector_type"),
        ("realtime", "0008_realtimestatus_realtime_re_data_so_aa3e1f_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="realtimestatus",
            index=models.Index(
                fields=["-timestamp"], name="realtime_re_timesta_dcfc71_idx"
            ),
        ),
    ]
