# Generated by Django 6.0.3 on 2026-08-13 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chargers", "0020_connector_chargers_co_chargep_0c31b6_idx"),
        ("realtime", "0009_realtimestatus_realtime_re_timesta_dcfc71_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrentStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("BLOCKED", "Blocked"),
                            ("CHARGING", "Charging"),
                            ("INOPERATIVE", "Inoperative"),
                            ("OUTOFORDER", "Out of order"),
                            ("PLANNED", "Planned"),
                            ("REMOVED", "Removed"),
                            ("RESERVED", "Reserved"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("data_source", models.CharField(max_length=255)),
                ("license_attribution", models.TextField(blank=True)),
                ("license_attribution_link", models.URLField(blank=True)),
            ],
            options={
                "get_latest_by": "timestamp",
                "abstract": False,
            },
        ),
        migrations.RenameModel(
            old_name="RealtimeStatus",
            new_name="PreviousStatus",
        ),
        migrations.RenameIndex(
            model_name="previousstatus",
            new_name="realtime_pr_timesta_6572f7_idx",
            old_name="realtime_re_timesta_dcfc71_idx",
        ),
        migrations.RenameIndex(
            model_name="previousstatus",
            new_name="realtime_pr_chargep_c838b7_idx",
            old_name="realtime_re_chargep_a4c9dc_idx",
        ),
        migrations.RenameIndex(
            model_name="previousstatus",
            new_name="realtime_pr_data_so_724c4c_idx",
            old_name="realtime_re_data_so_2b283c_idx",
        ),
        migrations.RenameIndex(
            model_name="previousstatus",
            new_name="realtime_pr_data_so_4bfb28_idx",
            old_name="realtime_re_data_so_aa3e1f_idx",
        ),
        migrations.AddField(
            model_name="currentstatus",
            name="chargepoint",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_status",
                to="chargers.chargepoint",
            ),
        ),
        migrations.AddIndex(
            model_name="currentstatus",
            index=models.Index(
                fields=["chargepoint"], name="realtime_cu_chargep_b4a82b_idx"
            ),
        ),
        migrations.RunSQL(
            """
            INSERT INTO realtime_currentstatus (status, timestamp, data_source, license_attribution, license_attribution_link, chargepoint_id)
            SELECT p.status, p.timestamp, p.data_source, p.license_attribution, p.license_attribution_link, p.chargepoint_id
            FROM (
                SELECT DISTINCT ON (chargepoint_id) chargepoint_id, status, timestamp, data_source, license_attribution, license_attribution_link
                FROM realtime_previousstatus
                ORDER BY chargepoint_id, timestamp DESC
            ) p;
            """,
            reverse_sql="DELETE FROM realtime_currentstatus;",
        ),
        migrations.AddConstraint(
            model_name="currentstatus",
            constraint=models.UniqueConstraint(
                fields=("chargepoint",), name="unique_current_status_per_chargepoint"
            ),
        ),
    ]
