# Generated by Django 5.2.6 on 2025-12-13 23:18

from django.db import migrations

from evmap_backend.data_sources.registry import get_data_source


def convert_realtime(apps, schema_editor):
    # converts previous NobilRealtime data into generic RealtimeState data
    NobilRealtimeData = apps.get_model("nobil", "NobilRealtimeData")
    RealtimeStatus = apps.get_model("realtime", "RealtimeStatus")
    Chargepoint = apps.get_model("chargers", "Chargepoint")

    if NobilRealtimeData.objects.count() == 0:
        return

    print("loading all chargers from nobil to be able to migrate realtime status")
    get_data_source("nobil").pull_data()

    for data in NobilRealtimeData.objects.all():
        nobil_id_without_country = str(int(data.nobil_id.split("_")[1]))
        try:
            chargepoint = Chargepoint.objects.get(
                site__data_source="nobil",
                site__id_from_source=nobil_id_without_country,
                id_from_source=data.evse_uid,
            )
            RealtimeStatus(
                chargepoint=chargepoint,
                status=data.status,
                timestamp=data.timestamp,
                data_source="nobil_realtime",
            ).save()
        except Chargepoint.DoesNotExist:
            if data.nobil_id.split("_")[0] in ["NOR", "SWE"]:
                print(
                    f"did not find correct chargepoint for realtime data with ID {data.nobil_id}/{data.evse_uid}"
                )


class Migration(migrations.Migration):

    dependencies = [
        ("nobil", "0002_nobilchargerstation_nobilconnector_nobilupdatestate"),
        ("realtime", "0001_initial"),
        ("chargers", "0006_alter_connector_connector_type"),
    ]

    operations = [
        migrations.RunPython(convert_realtime, atomic=True),
        migrations.RemoveField(
            model_name="nobilconnector",
            name="charging_station",
        ),
        migrations.DeleteModel(
            name="NobilRealtimeData",
        ),
        migrations.DeleteModel(
            name="NobilUpdateState",
        ),
        migrations.DeleteModel(
            name="NobilChargerStation",
        ),
        migrations.DeleteModel(
            name="NobilConnector",
        ),
    ]
