# Generated by Django 5.2.6 on 2025-12-13 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nobil", "0002_nobilchargerstation_nobilconnector_nobilupdatestate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nobilconnector",
            name="charging_station",
        ),
        migrations.DeleteModel(
            name="NobilRealtimeData",
        ),
        migrations.DeleteModel(
            name="NobilUpdateState",
        ),
        migrations.DeleteModel(
            name="NobilChargerStation",
        ),
        migrations.DeleteModel(
            name="NobilConnector",
        ),
    ]
