# Generated by Django 5.2.6 on 2025-12-13 23:18

from django.db import migrations

from evmap_backend.data_sources.registry import get_data_source


def get_nobil_data(apps, schema_editor):
    get_data_source("nobil").pull_data()


class Migration(migrations.Migration):

    dependencies = [
        ("nobil", "0002_nobilchargerstation_nobilconnector_nobilupdatestate"),
        ("realtime", "0001_initial"),
        ("chargers", "0006_alter_connector_connector_type"),
    ]

    operations = [
        migrations.RunPython(get_nobil_data),
        migrations.RunSQL(
            "INSERT INTO realtime_realtimestatus (status, timestamp, data_source, chargepoint_id) SELECT rt.status, rt.timestamp, 'nobil_realtime', cp.id FROM nobil_nobilrealtimedata AS rt INNER JOIN chargers_chargingsite AS cs ON (cs.data_source = 'nobil' AND cs.id_from_source = CAST(CAST(SPLIT_PART(rt.nobil_id, '_', 2) AS INTEGER) AS TEXT)) INNER JOIN chargers_chargepoint AS cp ON (cp.site_id = cs.id AND cp.id_from_source = rt.evse_uid);"
        ),
        migrations.RemoveField(
            model_name="nobilconnector",
            name="charging_station",
        ),
        migrations.DeleteModel(
            name="NobilRealtimeData",
        ),
        migrations.DeleteModel(
            name="NobilUpdateState",
        ),
        migrations.DeleteModel(
            name="NobilChargerStation",
        ),
        migrations.DeleteModel(
            name="NobilConnector",
        ),
    ]
