# Generated by Django 5.1.8 on 2025-05-25 10:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("goingelectric", "0001_initial"),
        ("goingelectric", "0002_alter_goingelectricchargelocation_url"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GoingElectricChargeLocation",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("address_city", models.CharField(blank=True, max_length=255)),
                ("address_country", models.CharField(blank=True, max_length=255)),
                ("address_postcode", models.CharField(blank=True, max_length=255)),
                ("address_street", models.CharField(blank=True, max_length=255)),
                ("network", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField(max_length=255)),
                ("fault_report", models.BooleanField()),
                ("verified", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="GoingElectricChargepoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=255)),
                ("power", models.FloatField()),
                ("count", models.IntegerField()),
                (
                    "chargelocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goingelectric.goingelectricchargelocation",
                    ),
                ),
            ],
        ),
    ]
