# Generated by Django 5.1.8 on 2025-05-25 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregator", "0001_initial"),
        ("goingelectric", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goingelectricchargelocation",
            name="aggregated_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_goingelectric",
                to="aggregator.chargelocation",
            ),
        ),
        migrations.AlterField(
            model_name="goingelectricchargepoint",
            name="chargelocation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chargepoints",
                to="goingelectric.goingelectricchargelocation",
            ),
        ),
    ]
