# Generated by Django 5.2.6 on 2025-10-04 19:43

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MontaTokens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(blank=True, max_length=255)),
                ("refresh_token", models.CharField(blank=True, max_length=255)),
                (
                    "access_token_expires",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "refresh_token_expires",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
