# Generated by Django 6.0.3 on 2026-03-10 21:41

import django.db.models.deletion
from django.db import migrations, models
from tqdm import tqdm


def populate_networks(apps, schema_editor):
    GoingElectricChargeLocation = apps.get_model(
        "goingelectric", "GoingElectricChargeLocation"
    )
    GoingElectricNetwork = apps.get_model("goingelectric", "GoingElectricNetwork")

    for charge_location in tqdm(GoingElectricChargeLocation.objects.all()):
        network_name = charge_location.network_name
        if network_name:
            network, created = GoingElectricNetwork.objects.get_or_create(
                name=network_name
            )
            charge_location.network = network
            charge_location.save()


class Migration(migrations.Migration):
    dependencies = [
        ("goingelectric", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoingElectricNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name="goingelectricchargelocation",
            old_name="network",
            new_name="network_name",
        ),
        migrations.AddField(
            model_name="goingelectricchargelocation",
            name="network",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chargelocations",
                to="goingelectric.goingelectricnetwork",
            ),
        ),
        migrations.RunPython(populate_networks),
        migrations.RemoveField(
            model_name="goingelectricchargelocation",
            name="network_name",
        ),
    ]
