# Generated by Django 6.0.3 on 2026-03-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goingelectric", "0002_goingelectricnetwork_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goingelectricchargepoint",
            name="type",
            field=models.CharField(
                choices=[
                    ("CCS", "CCS"),
                    ("CHAdeMO", "CHAdeMO"),
                    ("Typ1", "Type 1"),
                    ("Typ2", "Type 2"),
                    ("Typ3", "Type 3"),
                    ("Tesla Supercharger CCS", "Tesla Supercharger CCS"),
                    ("Tesla Supercharger", "Tesla Supercharger"),
                    ("Tesla HPC", "Tesla Roadster HPC"),
                    ("Schuko", "Schuko"),
                    ("Typ13", "Typ 13"),
                    ("Typ15", "Typ 15"),
                    ("Typ23", "Typ 23"),
                    ("Typ25", "Typ 25"),
                    ("CEE Rot", "CEE Red"),
                    ("CEE Blau", "CEE Blue"),
                    ("CEE+", "CEE+"),
                ],
                max_length=255,
            ),
        ),
    ]
