# Generated by Django 6.0.3 on 2026-03-13 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chargers", "0014_alter_connector_connector_type"),
        ("goingelectric", "0003_alter_goingelectricchargepoint_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="goingelectricchargelocation",
            name="match_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goingelectricchargelocation",
            name="matched_site",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="goingelectric_match",
                to="chargers.chargingsite",
            ),
        ),
        migrations.AddField(
            model_name="goingelectricnetwork",
            name="mapped_networks",
            field=models.ManyToManyField(
                blank=True, related_name="goingelectric_networks", to="chargers.network"
            ),
        ),
    ]
