# Generated by Django 6.0.3 on 2026-03-13 21:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goingelectric", "0004_goingelectricchargelocation_match_confidence_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goingelectricchargelocation",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True, srid=4326
            ),
        ),
    ]
