# Generated by Django 6.0.3 on 2026-04-01 20:36

import django.contrib.gis.db.models.fields
import django.contrib.gis.db.models.functions
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goingelectric", "0005_alter_goingelectricchargelocation_coordinates"),
    ]

    operations = [
        migrations.AddField(
            model_name="goingelectricchargelocation",
            name="coordinates_mercator",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.gis.db.models.functions.Transform(
                    django.db.models.functions.comparison.Cast(
                        "coordinates",
                        django.contrib.gis.db.models.fields.GeometryField(srid=4326),
                    ),
                    3857,
                ),
                output_field=django.contrib.gis.db.models.fields.PointField(srid=3857),
            ),
        ),
    ]
