# Generated by Django 5.2.6 on 2025-10-03 21:34

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models

import evmap_backend.chargers.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChargingSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_source", models.CharField(max_length=255)),
                ("id_from_source", models.CharField(max_length=255)),
                ("name", models.TextField()),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "site_evseid",
                    evmap_backend.chargers.fields.EVSEIDField(
                        blank=True, max_length=37
                    ),
                ),
                ("street", models.TextField(blank=True)),
                ("zipcode", models.CharField(blank=True, max_length=30)),
                ("city", models.CharField(blank=True, max_length=255)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("network", models.TextField(blank=True)),
                ("operator", models.TextField(blank=True)),
                (
                    "opening_hours",
                    evmap_backend.chargers.fields.OpeningHoursField(blank=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chargepoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_from_source", models.CharField(blank=True, max_length=255)),
                (
                    "evseid",
                    evmap_backend.chargers.fields.EVSEIDField(
                        blank=True, max_length=37
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chargepoints",
                        to="chargers.chargingsite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Connector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connector_type",
                    models.CharField(
                        choices=[
                            ("Type 1", "Type 1"),
                            ("CCS Type 1", "CCS Type 1"),
                            ("Type 2", "Type 2"),
                            ("CCS Type 2", "CCS Type 2"),
                            ("Type 3A", "Type 3A"),
                            ("Type 3C", "Type 3C"),
                            ("CHAdeMO", "CHAdeMO"),
                            ("Schuko", "Schuko (Type F)"),
                            ("NACS", "NACS (Tesla US)"),
                            ("Tesla Supercharger EU", "Tesla Supercharger EU (Type 2)"),
                            ("Tesla Roadster HPC", "Tesla Roadster HPC"),
                            ("iec60309x2single16", "CEE single-phase 16 A"),
                            ("iec60309x2three16", "CEE three-phase 16 A"),
                            ("iec60309x2three32", "CEE three-phase 32 A"),
                            ("iec60309x2three64", "CEE three-phase 63 A"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "connector_format",
                    models.CharField(
                        blank=True,
                        choices=[("socket", "socket"), ("cable", "cable")],
                        max_length=255,
                    ),
                ),
                ("max_power", models.FloatField()),
                (
                    "chargepoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connectors",
                        to="chargers.chargepoint",
                    ),
                ),
            ],
        ),
    ]
