# Generated by Django 5.2.6 on 2025-11-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chargers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="connector",
            name="id_from_source",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
