# Generated by Django 5.2.6 on 2025-11-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chargers", "0002_connector_id_from_source"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chargepoint",
            index=models.Index(
                fields=["site", "id_from_source"], name="chargers_ch_site_id_1bdbfa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chargingsite",
            index=models.Index(
                fields=["data_source", "id_from_source"],
                name="chargers_ch_data_so_e06323_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="connector",
            index=models.Index(
                fields=["chargepoint", "id_from_source"],
                name="chargers_co_chargep_3153a4_idx",
            ),
        ),
    ]
