# Generated by Django 5.1.4 on 2024-12-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NobilRealtimeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nobil_id", models.CharField(max_length=20)),
                ("evse_uid", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("BLOCKED", "Blocked"),
                            ("CHARGING", "Charging"),
                            ("INOPERATIVE", "Inoperative"),
                            ("OUTOFORDER", "Out of order"),
                            ("PLANNED", "Planned"),
                            ("REMOVED", "Removed"),
                            ("RESERVED", "Reserved"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
            options={
                "get_latest_by": "timestamp",
                "indexes": [
                    models.Index(
                        fields=["nobil_id", "evse_uid", "timestamp"],
                        name="nobil_nobil_nobil_i_0dc61f_idx",
                    )
                ],
            },
        ),
    ]
