# Generated by Django 5.1.5 on 2025-02-08 23:57

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("nobil", "0002_nobilchargerstation_nobilconnector"),
        ("nobil", "0003_nobilupdatestate"),
    ]

    dependencies = [
        ("nobil", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NobilChargerStation",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("ocpi_id", models.CharField(blank=True, max_length=255)),
                ("street", models.CharField(max_length=255)),
                ("house_number", models.CharField(max_length=10)),
                ("zip_code", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=255)),
                ("municipality_id", models.CharField(max_length=255)),
                ("municipality", models.CharField(max_length=255)),
                ("county_id", models.CharField(max_length=255)),
                ("county", models.CharField(max_length=255)),
                ("description_of_location", models.TextField(blank=True)),
                ("owned_by", models.CharField(blank=True, max_length=255)),
                ("operator", models.CharField(blank=True, max_length=255)),
                ("num_chargepoints", models.IntegerField()),
                ("image", models.CharField(blank=True, max_length=255)),
                ("available_chargepoints", models.IntegerField()),
                ("user_comment", models.TextField(blank=True)),
                ("contact_info", models.TextField(blank=True)),
                ("created", models.DateTimeField()),
                ("updated", models.DateTimeField()),
                ("station_status", models.IntegerField()),
                ("land_code", models.CharField(max_length=10)),
                ("international_id", models.CharField(max_length=255)),
                (
                    "location_type",
                    models.IntegerField(
                        choices=[
                            (1, "Street"),
                            (2, "Car park"),
                            (3, "Airport"),
                            (4, "Shopping center"),
                            (5, "Transport hub"),
                            (6, "Hotels & Restaurants"),
                            (7, "Gas station"),
                        ]
                    ),
                ),
                (
                    "availability",
                    models.IntegerField(
                        choices=[
                            (1, "Public"),
                            (2, "Visitors"),
                            (3, "Employees"),
                            (4, "By appointment"),
                            (5, "Residents"),
                        ]
                    ),
                ),
                ("open_24h", models.BooleanField()),
                ("parking_fee", models.BooleanField()),
                ("time_limit", models.BooleanField()),
                ("real_time_information", models.BooleanField()),
                (
                    "public_funding",
                    models.IntegerField(
                        choices=[
                            (1, "Oslo kommune"),
                            (2, "Transnova"),
                            (3, "Other"),
                            (4, "None"),
                            (5, "Klimasteget"),
                            (6, "Trafikkverket"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NobilConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (15, "All rechargeable vehicles"),
                            (1, "Rechargeable cars and vans"),
                            (6, "Rechargeable vans"),
                            (10, "Rechargeable medium or heavy trucks"),
                            (13, "Rechargeable buses"),
                            (14, "Rechargeable buses and trucks"),
                            (20, "Rechargeable boats"),
                            (22, "Rechargeable cars, vans and boats"),
                            (7, "All hydrogen vehicles"),
                            (8, "Hydrogen cars"),
                            (9, "Hydrogen trucks"),
                            (12, "Hydrogen and rechargeable cars and vans"),
                            (16, "Biogas vehicles"),
                            (11, "All vehicles"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "accessibility",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Open"),
                            (2, "Standard key"),
                            (3, "Other"),
                            (4, "RFID"),
                            (5, "Payment"),
                            (6, "Cellular Phone"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "energy_carrier",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Electricity"), (2, "Hydrogen"), (3, "Biogas")],
                        null=True,
                    ),
                ),
                (
                    "connector",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (31, "Type 1"),
                            (32, "Type 2"),
                            (30, "CHAdeMO"),
                            (39, "CCS/Combo"),
                            (40, "Tesla Connector Model"),
                            (50, "Type 2 + Schuko"),
                            (60, "Type 1/Type 2"),
                            (70, "Hydrogen"),
                            (82, "Biogas"),
                            (0, "Unspecified"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "charging_capacity",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (7, "3,6 kW - 230V 1-phase max 16A"),
                            (8, "7,4 kW - 230V 1-phase max 32A"),
                            (10, "11 kW - 400V 3-phase max 16A"),
                            (19, "20 kW DC - 500VDC max 50A"),
                            (11, "11 kW - 400V 3-phase max 32A"),
                            (37, "30 kW DC"),
                            (12, "43 kW - 400V 3-phase max 63A"),
                            (38, "62.5 kW DC"),
                            (13, "50 kW DC - 500VDC max 100A"),
                            (29, "75 kW DC"),
                            (23, "100 kW DC - 500VDC max 200A"),
                            (22, "135 kW DC - 480VDC max 270A"),
                            (24, "150 kW DC"),
                            (41, "175 kW DC"),
                            (42, "180 kW DC"),
                            (32, "200 kW DC"),
                            (30, "225 kW DC"),
                            (31, "250 kW DC"),
                            (33, "300 kW DC"),
                            (25, "350 kW DC"),
                            (36, "400 kW DC"),
                            (39, "500 kW DC"),
                            (0, "Unspecified"),
                            (16, "230V 3-phase max 16A"),
                            (17, "230V 3-phase max 32A"),
                            (18, "230V 3-phase max 63A"),
                            (26, "350 bar"),
                            (27, "700 bar"),
                            (34, "CBG"),
                            (35, "LBG"),
                        ],
                        null=True,
                    ),
                ),
                ("voltage", models.IntegerField(blank=True, null=True)),
                ("amperage", models.IntegerField(blank=True, null=True)),
                (
                    "payment_method",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Cellular Phone"),
                            (2, "Bank Card"),
                            (3, "Miscellaneous"),
                            (20, "Cellular Phone and Charging Card"),
                            (21, "Bank Card and Charging Card"),
                            (25, "Bank Card, Charging Card and Cellular Phone"),
                        ],
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("power_consumption", models.IntegerField(blank=True, null=True)),
                (
                    "connector_sensor_status",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "Vacant"), (1, "Busy (charging)")],
                        null=True,
                    ),
                ),
                (
                    "connector_error_status",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "In Service"), (1, "Error - Out of Service")],
                        null=True,
                    ),
                ),
                (
                    "connector_status",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Vacant"),
                            (1, "Busy (charging)"),
                            (2, "Reserved"),
                        ],
                        null=True,
                    ),
                ),
                ("evse_uid", models.CharField(blank=True, max_length=255)),
                ("fixed_cable", models.BooleanField(blank=True, null=True)),
                ("evse_id", models.CharField(blank=True, max_length=255)),
                ("connector_id", models.CharField(blank=True, max_length=255)),
                (
                    "charge_mode",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Mode 1"),
                            (2, "Mode 2"),
                            (3, "Mode 3"),
                            (4, "Mode 4"),
                        ],
                        null=True,
                    ),
                ),
                ("reservable", models.BooleanField(blank=True, null=True)),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                (
                    "charging_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nobil.nobilchargerstation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NobilUpdateState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_update", models.DateTimeField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
