# Generated by Django 5.2.6 on 2025-12-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UpdateState",
            fields=[
                (
                    "data_source",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("push", models.BooleanField()),
            ],
        ),
    ]
