# Generated by Django 6.0.3 on 2026-07-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_sources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthToken",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("access_token", models.CharField(max_length=255)),
                ("refresh_token", models.CharField(max_length=255)),
                ("access_token_expires", models.DateTimeField(null=True)),
                ("refresh_token_expires", models.DateTimeField(null=True)),
            ],
        ),
    ]
