from evmap_backend.data_sources import DataSource
from evmap_backend.data_sources.datex2.source import (
    Datex2AustriaDataSource,
    Datex2AustriaRealtimeDataSource,
    Datex2BelgiumEcoMovementDataSource,
    Datex2BelgiumMontaDataSource,
    Datex2DenmarkEcoMovementDataSource,
    Datex2DenmarkMontaDataSource,
    Datex2DenmarkOkDataSource,
    Datex2FinlandDataSource,
    Datex2LatviaEcoMovementDataSource,
    Datex2LatviaEcoMovementRealtimeDataSource,
    Datex2LuxembourgEcoMovementDataSource,
    Datex2MobilithekAudiChargingHubDataSource,
    Datex2MobilithekAudiChargingHubRealtimeDataSource,
    Datex2MobilithekChargecloudDataSource,
    Datex2MobilithekChargecloudRealtimeDataSource,
    Datex2MobilithekEClearingDataSource,
    Datex2MobilithekEClearingRealtimeDataSource,
    Datex2MobilithekEcoMovementDatex2DataSource,
    Datex2MobilithekEcoMovementRealtimeDataSource,
    Datex2MobilithekEluMobilityDataSource,
    Datex2MobilithekEluMobilityRealtimeDataSource,
    Datex2MobilithekEnbwDataSource,
    Datex2MobilithekEnbwRealtimeDataSource,
    Datex2MobilithekEnioDataSource,
    Datex2MobilithekEnioRealtimeDataSource,
    Datex2MobilithekEonDriveDataSource,
    Datex2MobilithekEonDriveRealtimeDataSource,
    Datex2MobilithekEroundDataSource,
    Datex2MobilithekEroundRealtimeDataSource,
    Datex2MobilithekEulektroDataSource,
    Datex2MobilithekEulektroRealtimeDataSource,
    Datex2MobilithekEwPricingDataSource,
    Datex2MobilithekEwPricingRealtimeDataSource,
    Datex2MobilithekFlaviaDataSource,
    Datex2MobilithekFlaviaRealtimeDataSource,
    Datex2MobilithekGlsMobilityDataSource,
    Datex2MobilithekGlsMobilityRealtimeDataSource,
    Datex2MobilithekGpJouleDataSource,
    Datex2MobilithekGpJouleRealtimeDataSource,
    Datex2MobilithekGridAndCoDataSource,
    Datex2MobilithekGridAndCoRealtimeDataSource,
    Datex2MobilithekLadebusinessDataSource,
    Datex2MobilithekLadebusinessRealtimeDataSource,
    Datex2MobilithekLadenetzDataSource,
    Datex2MobilithekLadenetzRealtimeDataSource,
    Datex2MobilithekLichtBlickDataSource,
    Datex2MobilithekLichtBlickRealtimeDataSource,
    Datex2MobilithekM8MitDataSource,
    Datex2MobilithekM8MitRealtimeDataSource,
    Datex2MobilithekMontaDataSource,
    Datex2MobilithekMontaRealtimeDataSource,
    Datex2MobilithekPumpDataSource,
    Datex2MobilithekQwelloDataSource,
    Datex2MobilithekQwelloRealtimeDataSource,
    Datex2MobilithekSmatricsDataSource,
    Datex2MobilithekSmatricsRealtimeDataSource,
    Datex2MobilithekTaubertConsultingDataSource,
    Datex2MobilithekTaubertConsultingRealtimeDataSource,
    Datex2MobilithekTeslaDataSource,
    Datex2MobilithekTeslaRealtimeDataSource,
    Datex2MobilithekUlmDataSource,
    Datex2MobilithekUlmRealtimeDataSource,
    Datex2MobilithekVaylensDataSource,
    Datex2MobilithekVaylensRealtimeDataSource,
    Datex2MobilithekVolkswagenGroupChargingDataSource,
    Datex2MobilithekVolkswagenGroupChargingRealtimeDataSource,
    Datex2MobilithekWirelaneDataSource,
    Datex2MobilithekWirelaneRealtimeDataSource,
    Datex2SloveniaDataSource,
    Datex2SloveniaRealtimeDataSource,
    Datex2SpainDataSource,
)
from evmap_backend.data_sources.fintraffic.source import FintrafficRealtimeDataSource
from evmap_backend.data_sources.goingelectric.source import GoingElectricDataSource
from evmap_backend.data_sources.irve.source import IrveFranceDataSource
from evmap_backend.data_sources.nobil.source import (
    NobilDataSource,
    NobilRealtimeDataSource,
)
from evmap_backend.data_sources.ocpi.source import (
    AllegoUkOcpiDataSource,
    AllegoUkOcpiRealtimeDataSource,
    BlinkUkOcpiDataSource,
    BlinkUkOcpiRealtimeDataSource,
    BpPulseUkOcpiDataSource,
    BpPulseUkOcpiRealtimeDataSource,
    ChargePointUkOcpiDataSource,
    ChargePointUkOcpiRealtimeDataSource,
    ChargyUkOcpiDataSource,
    ClenergyUkOcpiDataSource,
    CommunityByShellRechargeUkOcpiDataSource,
    CommunityByShellRechargeUkOcpiRealtimeDataSource,
    EsbUkOcpiDataSource,
    EsbUkOcpiRealtimeDataSource,
    EvPointUkOcpiDataSource,
    EvPointUkOcpiRealtimeDataSource,
    EvyeUkOcpiDataSource,
    EvyeUkOcpiRealtimeDataSource,
    FastnedUkOcpiDataSource,
    GeniepointUkOcpiDataSource,
    GoZeroUkOcpiDataSource,
    GridserveUkOcpiDataSource,
    InstavoltUkOcpiDataSource,
    IonityUkOcpiDataSource,
    IonityUkOcpiRealtimeDataSource,
    LidlUkOcpiDataSource,
    LidlUkOcpiRealtimeDataSource,
    MerUkOcpiDataSource,
    MfgUkOcpiDataSource,
    NdwNetherlandsOcpiDataSource,
    OspreyUkOcpiDataSource,
    PlugNGoUkOcpiDataSource,
    PlugNGoUkOcpiRealtimeDataSource,
    RawChargingUkOcpiDataSource,
    RawChargingUkOcpiRealtimeDataSource,
    RoadBelgiumOcpiDataSource,
    ScottishPowerUkOcpiDataSource,
    ShellRechargeUkOcpiDataSource,
    ShellRechargeUkOcpiRealtimeDataSource,
    SourceEvUkOcpiDataSource,
    SourceEvUkOcpiRealtimeDataSource,
    TeslaBelgiumOcpiDataSource,
    TeslaUkOcpiDataSource,
    UbitricityUkOcpiDataSource,
    UbitricityUkOcpiRealtimeDataSource,
    UrbanFoxUkOcpiDataSource,
)
from evmap_backend.data_sources.opendata_swiss.source import (
    OpendataSwissDataSource,
    OpendataSwissRealtimeDataSource,
)

DATA_SOURCE_CLASSES: list[type[DataSource]] = [
    # multiple countries
    GoingElectricDataSource,
    # Austria
    Datex2AustriaDataSource,
    Datex2AustriaRealtimeDataSource,
    # Germany
    # ElisoDataSource,  # Eliso is already included in the Eco-Movement data
    Datex2MobilithekEcoMovementDatex2DataSource,
    Datex2MobilithekEcoMovementRealtimeDataSource,
    Datex2MobilithekEnbwDataSource,
    Datex2MobilithekEnbwRealtimeDataSource,
    Datex2MobilithekLadenetzDataSource,
    Datex2MobilithekLadenetzRealtimeDataSource,
    Datex2MobilithekLadebusinessDataSource,
    Datex2MobilithekLadebusinessRealtimeDataSource,
    Datex2MobilithekEClearingDataSource,
    Datex2MobilithekEClearingRealtimeDataSource,
    Datex2MobilithekUlmDataSource,
    Datex2MobilithekUlmRealtimeDataSource,
    Datex2MobilithekWirelaneDataSource,
    Datex2MobilithekWirelaneRealtimeDataSource,
    Datex2MobilithekTeslaDataSource,
    Datex2MobilithekTeslaRealtimeDataSource,
    Datex2MobilithekSmatricsDataSource,
    Datex2MobilithekSmatricsRealtimeDataSource,
    Datex2MobilithekChargecloudDataSource,
    Datex2MobilithekChargecloudRealtimeDataSource,
    Datex2MobilithekEulektroDataSource,
    Datex2MobilithekEulektroRealtimeDataSource,
    Datex2MobilithekEroundDataSource,
    Datex2MobilithekEroundRealtimeDataSource,
    Datex2MobilithekMontaDataSource,
    Datex2MobilithekMontaRealtimeDataSource,
    Datex2MobilithekGridAndCoDataSource,
    Datex2MobilithekGridAndCoRealtimeDataSource,
    Datex2MobilithekEnioDataSource,
    Datex2MobilithekEnioRealtimeDataSource,
    Datex2MobilithekPumpDataSource,
    Datex2MobilithekM8MitDataSource,
    Datex2MobilithekM8MitRealtimeDataSource,
    Datex2MobilithekVaylensDataSource,
    Datex2MobilithekVaylensRealtimeDataSource,
    Datex2MobilithekEluMobilityDataSource,
    Datex2MobilithekEluMobilityRealtimeDataSource,
    Datex2MobilithekQwelloDataSource,
    Datex2MobilithekQwelloRealtimeDataSource,
    Datex2MobilithekEonDriveDataSource,
    Datex2MobilithekEonDriveRealtimeDataSource,
    Datex2MobilithekGlsMobilityDataSource,
    Datex2MobilithekGlsMobilityRealtimeDataSource,
    Datex2MobilithekLichtBlickDataSource,
    Datex2MobilithekLichtBlickRealtimeDataSource,
    Datex2MobilithekEwPricingDataSource,
    Datex2MobilithekEwPricingRealtimeDataSource,
    Datex2MobilithekGpJouleDataSource,
    Datex2MobilithekGpJouleRealtimeDataSource,
    Datex2MobilithekTaubertConsultingDataSource,
    Datex2MobilithekTaubertConsultingRealtimeDataSource,
    Datex2MobilithekVolkswagenGroupChargingDataSource,
    Datex2MobilithekVolkswagenGroupChargingRealtimeDataSource,
    Datex2MobilithekAudiChargingHubDataSource,
    Datex2MobilithekAudiChargingHubRealtimeDataSource,
    Datex2MobilithekFlaviaDataSource,
    Datex2MobilithekFlaviaRealtimeDataSource,
    # Luxembourg
    Datex2LuxembourgEcoMovementDataSource,
    # Netherlands
    NdwNetherlandsOcpiDataSource,
    # Sweden and Norway
    NobilDataSource,
    NobilRealtimeDataSource,
    # United Kingdom
    BpPulseUkOcpiDataSource,
    BpPulseUkOcpiRealtimeDataSource,
    IonityUkOcpiDataSource,
    IonityUkOcpiRealtimeDataSource,
    BlinkUkOcpiDataSource,
    BlinkUkOcpiRealtimeDataSource,
    EsbUkOcpiDataSource,
    EsbUkOcpiRealtimeDataSource,
    ShellRechargeUkOcpiDataSource,
    ShellRechargeUkOcpiRealtimeDataSource,
    CommunityByShellRechargeUkOcpiDataSource,
    CommunityByShellRechargeUkOcpiRealtimeDataSource,
    UbitricityUkOcpiDataSource,
    UbitricityUkOcpiRealtimeDataSource,
    RawChargingUkOcpiDataSource,
    RawChargingUkOcpiRealtimeDataSource,
    LidlUkOcpiDataSource,
    LidlUkOcpiRealtimeDataSource,
    EvPointUkOcpiDataSource,
    EvPointUkOcpiRealtimeDataSource,
    ChargePointUkOcpiDataSource,
    ChargePointUkOcpiRealtimeDataSource,
    ChargyUkOcpiDataSource,
    MfgUkOcpiDataSource,
    TeslaUkOcpiDataSource,
    InstavoltUkOcpiDataSource,
    GeniepointUkOcpiDataSource,
    ClenergyUkOcpiDataSource,
    GoZeroUkOcpiDataSource,
    EvyeUkOcpiDataSource,
    EvyeUkOcpiRealtimeDataSource,
    SourceEvUkOcpiDataSource,
    SourceEvUkOcpiRealtimeDataSource,
    FastnedUkOcpiDataSource,
    OspreyUkOcpiDataSource,
    MerUkOcpiDataSource,
    ScottishPowerUkOcpiDataSource,
    GridserveUkOcpiDataSource,
    UrbanFoxUkOcpiDataSource,
    PlugNGoUkOcpiDataSource,
    PlugNGoUkOcpiRealtimeDataSource,
    AllegoUkOcpiDataSource,
    AllegoUkOcpiRealtimeDataSource,
    # Latvia
    Datex2LatviaEcoMovementDataSource,
    Datex2LatviaEcoMovementRealtimeDataSource,
    # Lithuania
    # LithuaniaOcpiDataSource,  # Data is malformed (duplicate IDs)
    # Slovenia
    Datex2SloveniaDataSource,
    Datex2SloveniaRealtimeDataSource,
    # Denmark
    Datex2DenmarkEcoMovementDataSource,
    Datex2DenmarkMontaDataSource,
    Datex2DenmarkOkDataSource,
    # Belgium
    Datex2BelgiumEcoMovementDataSource,
    Datex2BelgiumMontaDataSource,
    RoadBelgiumOcpiDataSource,
    TeslaBelgiumOcpiDataSource,
    # Switzerland
    OpendataSwissDataSource,
    OpendataSwissRealtimeDataSource,
    # Finland
    Datex2FinlandDataSource,
    FintrafficRealtimeDataSource,
    # Spain
    Datex2SpainDataSource,
    # France
    IrveFranceDataSource,
]
DATA_SOURCE_REGISTRY: dict[str, type[DataSource]] = {
    cls.id: cls for cls in DATA_SOURCE_CLASSES
}


def setup_data_sources():
    """Perform initialization needed for all data sources"""
    for source_class in DATA_SOURCE_REGISTRY.values():
        source_class().setup()


def get_data_source(source_id: str) -> DataSource:
    """Get a data source instance by ID"""
    if source_id not in DATA_SOURCE_REGISTRY:
        raise ValueError(
            f"Unknown data source: {source_id}. Available sources: {', '.join(DATA_SOURCE_REGISTRY.keys())}"
        )

    return DATA_SOURCE_REGISTRY[source_id]()


def list_available_sources() -> list[str]:
    """List all available data source IDs"""
    return list(DATA_SOURCE_REGISTRY.keys())
