# Generated by Django 6.0.3 on 2026-03-22 18:28

import django.db.models.deletion
from django.db import migrations, models

import evmap_backend.pricing.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chargers", "0016_connector_is_dc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "is_adhoc",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the ad-hoc tariff offered by the CPO.",
                    ),
                ),
                ("data_source", models.CharField(blank=True, max_length=255)),
                (
                    "id_from_source",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        help_text="ISO 4217 currency code (e.g. EUR, CHF, GBP).",
                        max_length=3,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "min_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Minimum total price for a charging session using this tariff.",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Maximum total price for a charging session using this tariff.",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "chargepoints",
                    models.ManyToManyField(
                        blank=True, related_name="tariffs", to="chargers.chargepoint"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PriceComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ENERGY", "Energy (per kWh)"),
                            ("FLAT", "Flat fee (per session)"),
                            ("TIME", "Time (per minute, charging)"),
                            ("PARKING_TIME", "Parking time (per minute, not charging)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Price per unit (excl. or incl. tax depending on tax_included). Units: ENERGY in per kWh, TIME/PARKING_TIME in per minute, FLAT per session.",
                        max_digits=14,
                    ),
                ),
                (
                    "tax_included",
                    models.BooleanField(help_text="Whether the price includes tax."),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Tax rate as a percentage (e.g. 19.00 for 19% VAT).",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "step_size",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum granularity of billing. For ENERGY: in Wh. For TIME/PARKING_TIME: in seconds. For FLAT: must be 1.",
                    ),
                ),
                (
                    "min_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Minimum price for this component per session.",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Maximum price for this component per session.",
                        max_digits=14,
                        null=True,
                    ),
                ),
                ("day_of_week", evmap_backend.pricing.fields.DayOfWeekBitField()),
                (
                    "time_start",
                    models.TimeField(
                        blank=True,
                        help_text="Start time of day this component applies (inclusive).",
                        null=True,
                    ),
                ),
                (
                    "time_end",
                    models.TimeField(
                        blank=True,
                        help_text="End time of day this component applies (exclusive).",
                        null=True,
                    ),
                ),
                (
                    "min_power",
                    models.FloatField(
                        blank=True,
                        help_text="Minimum charging power in watts for this component to apply.",
                        null=True,
                    ),
                ),
                (
                    "max_power",
                    models.FloatField(
                        blank=True,
                        help_text="Maximum charging power in watts for this component to apply.",
                        null=True,
                    ),
                ),
                (
                    "min_duration",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum duration in seconds for this component to apply.",
                        null=True,
                    ),
                ),
                (
                    "max_duration",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum duration in seconds for this component to apply.",
                        null=True,
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_components",
                        to="pricing.tariff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NetworkTariffAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_dc",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="Filter: True = DC only, False = AC only, None = all.",
                        null=True,
                    ),
                ),
                (
                    "min_power",
                    models.FloatField(
                        blank=True,
                        help_text="Filter: minimum connector power in watts.",
                        null=True,
                    ),
                ),
                (
                    "max_power",
                    models.FloatField(
                        blank=True,
                        help_text="Filter: maximum connector power in watts.",
                        null=True,
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariff_assignments",
                        to="chargers.network",
                    ),
                ),
                (
                    "tariff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_assignment",
                        to="pricing.tariff",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="tariff",
            index=models.Index(
                fields=["data_source", "id_from_source"],
                name="pricing_tar_data_so_f7f2ef_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="tariff",
            constraint=models.UniqueConstraint(
                fields=("data_source", "id_from_source"),
                name="unique_tariff_per_source",
                nulls_distinct=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="networktariffassignment",
            constraint=models.UniqueConstraint(
                fields=("tariff",), name="unique_network_assignment_per_tariff"
            ),
        ),
    ]
