# Generated by Django 5.2.6 on 2026-01-31 15:30

from django.db import migrations, models

import evmap_backend.data_sources.ocpi.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OcpiConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_source", models.CharField(max_length=255, unique=True)),
                (
                    "token_a",
                    models.CharField(
                        blank=True,
                        default=evmap_backend.data_sources.ocpi.models.generate_token,
                        max_length=255,
                    ),
                ),
                ("token_b", models.CharField(blank=True, max_length=255)),
                ("token_c", models.CharField(blank=True, max_length=255)),
                ("url", models.CharField(blank=True, max_length=255)),
                ("party_id", models.CharField(blank=True, max_length=10)),
                ("locations_url", models.CharField(blank=True, max_length=255)),
                ("tariffs_url", models.CharField(blank=True, max_length=255)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("version", models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
