# Generated by Django 5.2.6 on 2025-12-02 21:23

from django.db import migrations, models

import evmap_backend.apikeys.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "key",
                    models.CharField(
                        default=evmap_backend.apikeys.models._generate_api_key,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
